Updated README.md [9925]
eProsima/Discovery-Server pull request #18
Opened 2020-11-16 09:31 UTC by rsanchez15

This PR updates the README.md accordingly to the Discovery Server 2.0.

2020-11-18 10:41 UTC, jparisu commented on README.md
> +In order to use the Discovery Server tool, its necessary to have a compatible version of
```suggestion
In order to use the Discovery Server tool, it is necessary to have a compatible version of
```

2020-11-18 11:05 UTC, EduPonz requested changes
Also check italics/`code-block` consistency

2020-11-18 11:05 UTC, EduPonz commented on README.md
>  ```xml
comments in here look weird

2020-11-18 11:05 UTC, EduPonz commented on README.md
> +	- ``<discoveryServersList>``: specifies the server or servers linked with a Client/Server.
```suggestion
	- ``<discoveryServersList>``: specifies the server or servers to which a Client/Server connects.
```

2020-11-18 11:05 UTC, EduPonz commented on README.md
> +number and the optional *d* denotes a debug builds) is set up from one XML profiles files passed as command-line arguments.
```suggestion
number and the optional *d* denotes a debug build) is set up from one XML profiles files passed as command-line arguments.
```

2020-11-23 11:54 UTC, EduPonz requested changes

2020-11-23 11:54 UTC, EduPonz commented on README.md
> +The [RTPS standard](http://www.omg.org/spec/DDSI-RTPS/2.3) specifies in section 8.5 a non-centralized, distributed
```suggestion
The [RTPS standard](http://www.omg.org/spec/DDSI-RTPS/2.3) specifies in section 8.5 a non-centralized, distributed,
```

2020-11-23 11:54 UTC, EduPonz commented on README.md
> +simple discovery mechanism. This mechanism was devised to allow interoperability among independent
```suggestion
simple discovery mechanism. This mechanism was devised to allow interoperability between independent
```

2020-11-23 11:54 UTC, EduPonz commented on README.md
> +There are several scenarios were the simple discovery mechanism is unsuitable or plainly cannot be
```suggestion
There are several scenarios where the simple discovery mechanism is unsuitable, or it just simply cannot be
```

2020-11-23 11:54 UTC, EduPonz commented on README.md
> +THIRDPARTY=ON or because those libraries have been specifically installed.
```suggestion
`THIRDPARTY=ON|FORCE` or because those libraries have been specifically installed.
```

2020-11-23 14:18 UTC, EduPonz approved these changes
LGTM

2020-11-23 14:18 UTC, merged