SUPER_CLIENT tests
eProsima/Discovery-Server pull request #24
Opened 2021-02-16 10:16 UTC by jparisu

https://github.com/eProsima/Fast-DDS/pull/1763

2021-02-19 13:04 UTC, MiguelBarro approved these changes
test 33 fails on Windows because at the end of the `main` function the `Domain::stopAll()` triggers a segmentation fault.
The snapshot file is generated on ~DSManager() thus is never created and forces test failure.
This is an unrelated issue the tests LGTM.

2021-03-05 09:17 UTC, EduPonz requested changes

2021-03-05 09:17 UTC, EduPonz commented on src/DSManager.cpp
> +        atts.rtps.builtin.discovery_config.discoveryProtocol != DiscoveryProtocol_t::SUPER_CLIENT)
We need some guards here for backwards compatibility. `SUPER_CLIENT` will only be from 2.3, but this should run for older branches too. Look at #27

2021-03-05 09:29 UTC, EduPonz requested changes

2021-03-05 09:29 UTC, EduPonz commented on src/DSManager.cpp
> +#if FASTRTPS_VERSION_MAJOR >= 2 && FASTRTPS_VERSION_MINOR >= 1
```suggestion
#if FASTRTPS_VERSION_MAJOR >= 2 && FASTRTPS_VERSION_MINOR >= 3
```

2021-03-05 10:06 UTC, EduPonz approved these changes

2021-03-05 10:06 UTC, merged