Reconnection tests [12522]
eProsima/Discovery-Server pull request #45
Opened 2021-10-06 05:32 UTC by rsanchez15

Reverts eProsima/Discovery-Server#44.

This PR restore the changes made in https://github.com/eProsima/Discovery-Server/pull/41. 
Do not merge until https://github.com/eProsima/Fast-DDS/pull/2247 is merged.

2021-10-06 05:47 UTC, rsanchez15 commented
This PR is approved in favor of #41.

2021-11-04 15:02 UTC, jsantiago-eProsima requested changes
Partial Review pending xml and snapshot check

2021-11-04 15:25 UTC, jparisu commented on src/main.cpp
>  #include <fastdds/dds/log/StdoutErrConsumer.hpp>
:+1:

2021-11-04 15:25 UTC, jparisu commented on src/main.cpp
> +    #endif
:+1:

2021-11-07 19:57 UTC, jsantiago-eProsima approved these changes
LGTM

2021-11-16 09:13 UTC, EduPonz approved these changes
LGTM

2021-11-22 11:23 UTC, EduPonz approved these changes
LGTM

2021-11-22 11:23 UTC, merged